### ISSUE TITLE
Flask run problem

### ISSUE THREAD

**Issue by WolfTwi97** [WiiLink24/room-server#63]
>flask run --host :: --port 80
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python311\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\flask\cli.py", line 1063, in main
    cli.main()
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\flask\cli.py", line 911, in run_command
    raise e from None
  File "C:\Program Files\Python311\Lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
          ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\room-server-master\room.py", line 40, in <module>
    @app.before_first_request
     ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Flask' object has no attribute 'before_first_request'. Did you mean: '_got_first_request'?

**Comment by WaqarAnwar** [comment]
Try: flask run --port 80

**Comment by WolfTwi97** [comment]
> Try: flask run --port 80

It gives me the same error.

**Comment by noahpistilli** [comment]
Fixed in [d92f015](https://github.com/WiiLink24/room-server/commit/d92f01597785beeccb4adc389a0c7232bfcace62)
